version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://vccrm:vccrm@db:5432/vccrm
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=vccrm
      - POSTGRES_PASSWORD=vccrm
      - POSTGRES_DB=vccrm
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
